select @@SERVERNAME


ALTER AVAILABILITY GROUP [abi-sql-ag] MODIFY REPLICA ON N'abi-sql-0' WITH (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('abi-sql-1')));
GO

ALTER AVAILABILITY GROUP [abi-sql-ag] MODIFY REPLICA ON N'abi-sql-1' WITH (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('abi-sql-0')));
GO




ALTER AVAILABILITY GROUP [abi-sql-ag] MODIFY REPLICA ON N'abi-sql-0' WITH (SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://abi-sql-0:1433'));
GO

ALTER AVAILABILITY GROUP [abi-sql-ag] MODIFY REPLICA ON N'abi-sql-1' WITH (SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://abi-sql-1:1433'));
GO
